apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-t3vl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-t3vl@sha256:235722a005a0191d6891e4651471616e0d12f3e0664652f479073647d5ff9a05
        name: my-nodejs
        resources: {}
status: {}
